#!/bin/bash

echo "🔧 Updating Vercel Environment Variables..."
echo ""
echo "Run these commands one by one:"
echo ""
echo "npx vercel env add REACT_APP_RESEARCH_GRAPH"
echo "# When prompted, enter: 0x1f1cc3c6024c29d091ab299450b5F8C8f978151F"
echo ""
echo "npx vercel env add REACT_APP_RESEARCH_TOKEN"
echo "# When prompted, enter: 0x16ebbf03eB84e814533CE437cB23DAf73d4Ec998"
echo ""
echo "npx vercel env add REACT_APP_USDC"
echo "# When prompted, enter: 0x5d2F8B3E342dCD5E48dFF93Dfba48bEBA24b9dBA"
echo ""
echo "npx vercel env add REACT_APP_NETWORK"
echo "# When prompted, enter: flare"
echo ""
echo "npx vercel env add REACT_APP_CHAIN_ID"
echo "# When prompted, enter: 114"
echo ""
echo "Then redeploy:"
echo "npx vercel --prod"
